### ISSUE TITLE
Missing Commit data

### ISSUE THREAD

**Issue by perploug** [zalando-incubator/roadblock#2]
## Expected Behavior
To have dates, message and numbers of comments on each commit 

## Actual Behavior
There was either no column or the data was not mapped correctly.

## Steps to Reproduce the Problem

  1. Run the data fetch and place a breakpoint in the save method to see the data fetched
  1. Place breakpoint in write commit to see that the issue is a wrongly configured mapper

**Comment by princiya** [comment]
Fixed in PR #3
